# Dynamic TLS configuration — default secure options applied to all routers.

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_AES_128_GCM_SHA256
      sniStrict: true
